spring:
  application:
    name: JobSearch
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  mail:
    host: smtp.gmail.com
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  #  ========== OAuth2.0 Config

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
#  ========== OAuth2.0 Config


logging:
  level:
    root: info
    org:
    springframework:
      security: debug
  file:
    path: logs
server:
  port: 8099
