INSERT INTO vacancy (name, description, categoryId, salary, expFrom, expTo, isActive, authorId, createdDate, updatedTime)
VALUES
-- 3
('Middle Бэкенд-разработчик', 'Разработка REST API на Java',
 (SELECT id FROM category WHERE name = 'Бэкенд-разработчик' LIMIT 1), 58000.00, 3, 6, TRUE,
(SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
-- 4
('Junior Фронтенд-разработчик', 'Поддержка UI компонентов',
 (SELECT id FROM category WHERE name = 'Младший Фронтенд-разработчик' LIMIT 1), 45000.00, 0, 2, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
-- 5–15
('Фронтенд-разработчик Vue.js', 'Разработка SPA на Vue.js',
 (SELECT id FROM category WHERE name = 'Фронтенд-разработчик' LIMIT 1), 60000.00, 2, 5, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('Fullstack-разработчик', 'Работа с фронтом и бэком',
 (SELECT id FROM category WHERE name = 'Бэкенд-разработчик' LIMIT 1), 75000.00, 4, 7, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('Backend Dev Go', 'Разработка микросервисов на Go',
 (SELECT id FROM category WHERE name = 'Бэкенд-разработчик' LIMIT 1), 80000.00, 5, 8, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('React Developer', 'SPA-приложения на React',
 (SELECT id FROM category WHERE name = 'Фронтенд-разработчик' LIMIT 1), 70000.00, 3, 6, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('Стажер Бэкенд', 'Участие в проектах под менторством',
 (SELECT id FROM category WHERE name = 'Младший Бэкенд-разработчик' LIMIT 1), 30000.00, 0, 1, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('Vue Developer Junior', 'Фронтенд на Vue под наставничеством',
 (SELECT id FROM category WHERE name = 'Младший Фронтенд-разработчик' LIMIT 1), 42000.00, 0, 2, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('Senior Fullstack Dev', 'Архитектура, дизайн, разработка',
 (SELECT id FROM category WHERE name = 'Старший Бэкенд-разработчик' LIMIT 1), 90000.00, 6, 10, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('Angular Developer', 'Фронтенд на Angular',
 (SELECT id FROM category WHERE name = 'Фронтенд-разработчик' LIMIT 1), 68000.00, 3, 5, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('Junior Java Developer', 'Изучение Java EE, участие в проектах',
 (SELECT id FROM category WHERE name = 'Младший Бэкенд-разработчик' LIMIT 1), 40000.00, 0, 2, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('Middle Frontend', 'Разработка UI и UX',
 (SELECT id FROM category WHERE name = 'Фронтенд-разработчик' LIMIT 1), 62000.00, 3, 6, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW()),
('React + Node Developer', 'Полный стек на JS',
 (SELECT id FROM category WHERE name = 'Бэкенд-разработчик' LIMIT 1), 77000.00, 4, 7, TRUE,
 (SELECT id FROM users WHERE email = 'maria.petrova@employer.com' LIMIT 1), NOW(), NOW());




INSERT INTO resume (applicantId, name, categoryId, salary, isActive, createdDate, updateTime)
VALUES
-- 3–15
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Middle Бэкенд',
(SELECT id FROM category WHERE name = 'Бэкенд-разработчик' LIMIT 1), 72000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Junior Frontend',
 (SELECT id FROM category WHERE name = 'Младший Фронтенд-разработчик' LIMIT 1), 50000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Fullstack',
 (SELECT id FROM category WHERE name = 'Старший Бэкенд-разработчик' LIMIT 1), 85000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Go Developer',
 (SELECT id FROM category WHERE name = 'Бэкенд-разработчик' LIMIT 1), 78000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Vue Frontend',
 (SELECT id FROM category WHERE name = 'Фронтенд-разработчик' LIMIT 1), 62000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Junior Backend',
 (SELECT id FROM category WHERE name = 'Младший Бэкенд-разработчик' LIMIT 1), 45000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Angular Frontend',
 (SELECT id FROM category WHERE name = 'Фронтенд-разработчик' LIMIT 1), 63000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Node.js Dev',
 (SELECT id FROM category WHERE name = 'Бэкенд-разработчик' LIMIT 1), 71000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: React Frontend',
 (SELECT id FROM category WHERE name = 'Фронтенд-разработчик' LIMIT 1), 65000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Стажер Backend',
 (SELECT id FROM category WHERE name = 'Младший Бэкенд-разработчик' LIMIT 1), 32000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Junior Java',
 (SELECT id FROM category WHERE name = 'Младший Бэкенд-разработчик' LIMIT 1), 47000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Middle Frontend',
 (SELECT id FROM category WHERE name = 'Фронтенд-разработчик' LIMIT 1), 61000.00, TRUE, NOW(), NOW()),
((SELECT id FROM users WHERE name = 'Иван' LIMIT 1), 'Резюме Ивана: Fullstack JS',
 (SELECT id FROM category WHERE name = 'Бэкенд-разработчик' LIMIT 1),
